import './globals.css';
import type { Metadata } from 'next';
import Header from 'components/Header/Header';
import Navbar from 'components/Navbar';
import Footer from 'components/Footer';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'The Snowboard Store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-slate-200 flex flex-col min-h-screen min-w-screen">
        <div className="sticky top-0 z-10">
          <Header />
          <Navbar />
        </div>
        <main className="flex-grow w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
